name: Django Deploy CD
on:
  push:
    branches: [ main ]

env:
  status: create

jobs:
  create-repo:
    runs-on: ubuntu-latest
    # don't run locally
    steps:
      - name: Create a repository
        if: ${{ env.status == 'create' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd Development            
            git clone ${{secrets.REPO_URL}} -b main
            cd ${{ github.event.repository.name }}
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py runserver 0.0.0.0:8002

  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Repository update
        if: ${{ env.status == 'update' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd Development            
            git pull ${{secrets.REPO_URL}}
            cd ${{ github.event.repository.name }}
            source venv/bin/activate
            pip install -r requirements.txt
            ./manage.py runserver 0.0.0.0:8002
