name: Django Deploy CD
on:
  push:
    branches: [ main ]



env:
  status: create

jobs:
  create-repo:
    runs-on: ubuntu-latest
    # don't run locally
    steps:
      - name: Create a repository
        if: ${{ env.status == 'create' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd Development            
            git clone ${{secrets.REPO_URL}} -b main
            cd ${{ github.event.repository.name }}
            ls

            docker-compose up -d

  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Repository update
        if: ${{ env.status == 'update' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd Development
            cd ${{ github.event.repository.name }}
            git pull
            
            docker compose down
            docker rmi develop_image
            docker-compose up -d
