name: Django Deploy CD
on:
  push:
    branches: [ main ]

env:
  status: update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        # don't run locally
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd Development            
            git pull ${{secrets.REPO_URL}}
            cd ${{ github.event.repository.name }}
#            python3 -m venv venv
            source venv/bin/activate
            pip freeze
#            pip install -r requirements.txt

            

#            docker-compose down
#            docker-compose up --build -d
