
name: Test github file


on:
  push:
#    branches: [ developer ]
    paths:
      - '**test-github.yml'



jobs:
  job1:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [""]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.12'
      - name: Step1
        shell: python
        run: |
          print("Salom dunyo!")
          import os
          print("Print environ path - ", os.environ['PATH'])
      - name: GitHub Sha
        run: echo "${{ github.sha }}"

#env:
#  PASS: ${{ 6069 }}
#  myAGE: ${{ 19 }}
#  Developer: ${{ true }}


#if: ${{ success() }}

#if: ${{ always() }}

#if: ${{ cancelled() }} Agar jarayon bekor bo'lsa true qaytaradi

#if: ${{ failure() }} Agar yuqoridagi ishlarni birortasi bajarilmasa true

#timeout_minutes: 30  30 mindan keyin ishlayotgan job yoki jobslar yopiladi


# Har kuni soat 5:30 va 17:30 da ishga tushiradi
#on:
#  schedule:
#    - cron: '30 5,17 * * *'


# *  *  *  *  *
# minute
#     hour
#        day
#           month
#              week

# 15 * * * *  har kuni har 15 min.da run bo'ladi




# Build nomli oqim main branchda ishlaganda ishga tushadi
#on:
#  workflow_run:
#    workflows: ["Build"]
#    types: [requested]
#    branches:
#      - "main"


# Build nomli oqim developer branchda ishlamaganda ishga tushadi
#on:
#  workflow_run:
#    workflows: ["Build"]
#    types: [requested]
#    branches-ignore:
#      - "developer"



# Bu faqat pull qilinganda va push qilinmaganda ishlaydi
#steps:
#  - name: First step
#    if: ${{ github.event_name == 'pull_request' && github.event_name != 'push' }}
